### PR TITLE
Updating source files and adding build process

### PR DESCRIPTION
**Pull request by aaronbell**
Made some minor updates to the font file to prep it for release on Google Fonts and added a build process for the font.

### CODE REVIEW

**Comment by aaronbell** [comment]
When you have the chance, please take a look at the TTF provided in this PR (attached below) and let me know if it meets your expectations.
[OtomanopeeOne-Regular.ttf.zip](https://github.com/Gutenberg-Labo/Otomanopee/files/5532933/OtomanopeeOne-Regular.ttf.zip)


If you're OK with this PR, please merge it in :)

**Comment by Gutenberg-Labo** [comment]
Thank you very much for the review.
​There are two points I would like to ask you to check before merging.

​First, when checking TTF, I noticed that there was one glyph with extra points due to misplaced shapes (Lozenge, U+25CA), so I modified the source.
I'm really sorry for the work you've done, but please update it again.

Second, the font family name has been changed from "Otomanope" to "OtomanopeeOne", tell me why you need to add One.
I've heard that the vendor's alphabet have to be removed (GL-Otomanopee -> Otomanopee), but I haven't heard of further changes needed.
I could check the case of other authors and found that one seems to be added One to the name (e.g. ManiackersDesign), but another remained the same (e.g. ​YuseiMagic). Is there any regulation?

**Comment by aaronbell** [comment]
Oh! OK. 

As for the 'One' the [Google spec](https://github.com/googlefonts/gf-docs/tree/master/Spec#single-weight-families) states that for single weight families, if the overall weight of the font is heavier than what we would consider a "Regular", to add the name "One" to it. That way, if in the future you (or Google) decide to expand the font weight range, it is easy to do so without impacting users who are already using the font.

**Comment by Gutenberg-Labo** [comment]
Thank you for the explanation about adding 'One'.
Oh, it is surely single weight and heavier than Regular and exactly applies to Google spec. I understand :)

**Comment by aaronbell** [comment]
All good! Updated font file. Please merge this in and we'll be all set.

**Comment by Gutenberg-Labo** [comment]
Very much appreciate your help.  I've merged it in!

**Pull request merged**
